name: 🚀 Node.js CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    name: 🔍 Test & Build (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
      - name: 🛒 Checkout code
        uses: actions/checkout@v4
        
      - name: ⎔ Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      - name: 📦 Install dependencies
        run: npm ci
        env:
          CI: true
          
      - name: 🏗️ Build project
        run: npm run build --if-present
        if: success()
        
      - name: 🧪 Run tests
        run: npm test
        env:
          CI: true
          
      - name: 📊 Test summary
        if: always()
        run: |
          echo "✅ Tests completed for Node ${{ matrix.node-version }}"
          echo "📦 Node version: $(node -v)"
          echo "🔄 npm version: $(npm -v)"
