# Workflow para CI com Node.js - Várias etapas organizadas

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.x", "20.x", "22.x"]  # Versões do Node.js a testar

    steps:
      # ────────────────
      # ➤ Etapa 1: Checkout do repositório
      - name: 📦 Checkout do código
        uses: actions/checkout@v4

      # ────────────────
      # ➤ Etapa 2: Configurar Node.js e cache
      - name: 🧱 Configurar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # ────────────────
      # ➤ Etapa 3: Instalar dependências
      - name: 🔧 Instalar dependências (npm ci)
        run: npm ci

      # ────────────────
      # ➤ Etapa 4: Build do projeto (opcional)
      - name: 🛠️ Executar build (se disponível)
        run: npm run build --if-present

      # ────────────────
      # ➤ Etapa 5: Rodar testes
      - name: ✅ Rodar testes
        run: npm test
